# Generated by Django 3.0.6 on 2020-05-12 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0003_auto_20200512_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('B', 'Book'), ('N', 'Note'), ('R', 'Reading')], default='R', max_length=1),
        ),
    ]
