# Generated by Django 3.0.6 on 2020-05-12 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0004_auto_20200512_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='contains_notes',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('B', 'Book'), ('R', 'Reading')], default='R', max_length=1),
        ),
    ]
