# Generated by Django 3.0.6 on 2020-05-13 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0005_auto_20200512_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='static/registrations/images/default_male_dp.jpeg', upload_to='profile_pics'),
        ),
    ]
