# Generated by Django 3.0.6 on 2020-05-13 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0008_book_interested_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='year',
            field=models.SmallIntegerField(default=1),
        ),
    ]
