# Generated by Django 3.0.2 on 2020-05-14 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0010_book_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='seller_books', to='registrations.UserProfile'),
            preserve_default=False,
        ),
    ]
