# Generated by Django 3.0.6 on 2020-05-15 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0013_auto_20200515_0647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='description',
            new_name='additional_details',
        ),
        migrations.RenameField(
            model_name='bookset',
            old_name='description',
            new_name='additional_details',
        ),
    ]
