# Generated by Django 3.0.6 on 2020-05-16 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0017_auto_20200516_0631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ineterested_users',
            field=models.ManyToManyField(blank=True, related_name='books_wishlist', to='registrations.UserProfile'),
        ),
        migrations.AlterField(
            model_name='bookset',
            name='ineterested_users',
            field=models.ManyToManyField(blank=True, related_name='booksets_wishlist', to='registrations.UserProfile'),
        ),
    ]
