# Generated by Django 3.0.6 on 2020-05-16 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0019_bookset_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookset',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrations.UserProfile'),
        ),
    ]
