# Generated by Django 3.0.6 on 2020-05-16 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0022_userprofile_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='default_male_dp.png', upload_to='profile_pics'),
        ),
    ]
