# Generated by Django 3.0.6 on 2020-05-17 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0023_auto_20200516_1359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookset',
            old_name='ineterested_users',
            new_name='interested_users',
        ),
    ]
