# Generated by Django 3.0.6 on 2020-05-24 13:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0024_auto_20200517_0555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='year',
        ),
        migrations.RemoveField(
            model_name='bookset',
            name='year',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='year',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='semester',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)]),
        ),
        migrations.AlterField(
            model_name='book',
            name='semester',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)]),
        ),
    ]
